apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/openshift-pipeline/openshift-pipelines-pipelines-operator-bundle-container-index@sha256:b654ba0e94edc12ef14f255a7493833e9d2f04658ac97211d78200c1dc06c27b
  displayName: custom-operators
  updateStrategy:
    registryPoll:
      interval: 30m
