apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: test-file-changed-
  namespace: enatan-tenant
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && files.all.exists(x, x.matches('test.go'))
spec:
  params:
    - name: TEST
      value: "test file changed"
  pipelineSpec:
    tasks:
      - name: echo-hello
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "$(params.TEST)"                
