name: update-osp-nightly
run-name: Check for OSP nightly and create a PR
on:
  schedule:
    - cron: '*/2 0 * * *'
  workflow_dispatch:
permissions: {}
jobs:
  update-osp-nightly:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Update index image digest
        run: |
          tag="v4.14-candidate"
          inspected=$(skopeo inspect docker://quay.io/openshift-pipeline/openshift-pipelines-pipelines-operator-bundle-container-index:$tag)
          created=$(echo "$inspected" | jq -r '.Created')
          echo "DEBUG: Found tag $tag created: $created"
          digest=$(echo "$inspected" | jq -r '.Digest')
          echo "DEBUG: Tag digest: $digest"
          sed -i -E "s/sha256:[0-9a-f]{64}/${digest}/g" catalog-source.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "[new-osp-nightly-build] automated change"
          title: Automated changes by update OSP nightly
          body: |
            Automated changes by [update-osp-nightly]

            Found new OSP nightly build
